Awesome books: refactor to use JavaScript classes
petudeveloper/Awesome-books pull request #2
Opened 2021-08-10 20:57 UTC by Hamzaoutdoors

- Added Professional README file
- Added linters configuration (HTML, CSS and JS)
- Added book creation with object constructor
- Added fix for form submission
- Added event listener to add & remove books
- Added Class methods to remove book object from books array
- Added local storage functionality
- Added fix for local storage & fix linters errors

2021-08-10 23:15 UTC, de-scholar requested changes
Hi @Hamzaoutdoors and @petumazo , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-10 23:15 UTC, de-scholar commented on JS/main.js
>    const books = document.getElementById('books');
- [ ] All of the functionality of this project should be embedded inside classes, please move this function in your class

2021-08-11 15:57 UTC, petudeveloper commented on JS/main.js
>    const books = document.getElementById('books');
Issue solved, thanks for the feedback.

2021-08-11 15:58 UTC, petumazo commented
@de-scholar Thanks for the feedback, we followed your suggestions and embedded all of the functionalities inside a class.

2021-08-11 16:03 UTC, hemant-soni-vst-au4 approved these changes
Hi @Hamzaoutdoors and @petumazo, 

Well done on making the requested changes. 👍 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

## Congratulations! 🎉 

![Alt Text](https://media.giphy.com/media/jkZhf5HyZkLbBzzZsn/giphy.gif)

Cheers and happy coding 😃

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. You can mention me (@hemant-soni-vst-au4) so I can see your comments and respond.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-11 16:11 UTC, merged